%YAML:1.0

# debug
enable_perf_output: 1
warn_imu_duration: 0
use_mag: 1  # 使用磁力计


#common parameters
imu: 1         
num_of_cam: 2  

imu_topic: "/mavros/imu/data_raw"
mag_topic: "/mavros/imu/mag"
image0_topic: "/iris_swarm/stereo_camera/left/image_raw"
image1_topic: "/iris_swarm/stereo_camera/right/image_raw"
output_path: "/swarm/fisheye_ws/output"


cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 848
image_height: 480

imu_freq: 250
image_freq: 30
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't have extrinsic parameters. We will estimate extrinsic parameters online.
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0,0,1,0.1,
          -1,0,0,0.045,
          0,-1,0,0,
          0,0,0,1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0,0,1,0.1,
          -1,0,0,-0.045,
          0,-1,0,0,
          0,0,0,1]
# imu 飞控，从mavros拿到是flu
# cam 相机坐标系，右下前


#Gpu accleration support
use_gpu: 1
use_nvidia_vpi: 0

enable_depth: 0

#feature traker paprameters
use_orb: 0              # use orb feature or not
max_cnt: 120            # max feature number in feature tracking
max_solve_cnt: 50       # Max Point for solve; highly influence performace
depth_estimate_baseline: 0.095
thres_outlier : 3.0
tri_max_err: 1.5

min_dist: 30            # min distance between two features 
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 7.1516e-2         # accelerometer measurement noise standard deviation. # 0.0186
gyr_n: 2.7775e-3         # gyroscope measurement noise standard deviation.     # 0.00018665
acc_w: 4.2108e-3         # accelerometer bias random work noise standard deviation.  # 0.06
gyr_w: 8.068e-5        # gyroscope bias random work noise standard deviation.     # 0.00038 
g_norm: 9.8     # gravity magnitude

mag_measure_noise: 1.0e-6
mag_world_noise: 1e-9
mag_bias_noise: 1e-12

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0048                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
